### ISSUE TITLE
error while running buildHaplotypeGraph command

### ISSUE THREAD

**Issue by beantkapoor786** [maize-genetics/rPHG2#12]
Hello, I am running this command but getting the following error
```R
graph <- locCon |> buildHaplotypeGraph()
```
Error -
```R
Exception in thread "DefaultDispatcher-worker-1" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.LinkedHashMap.newNode(LinkedHashMap.java:257)
	at java.base/java.util.HashMap.putVal(HashMap.java:629)
	at java.base/java.util.HashMap.putMapEntries(HashMap.java:514)
	at java.base/java.util.HashMap.putAll(HashMap.java:783)
	at htsjdk.variant.vcf.VCFSimpleHeaderLine.initialize(VCFSimpleHeaderLine.java:111)
	at htsjdk.variant.vcf.VCFSimpleHeaderLine.<init>(VCFSimpleHeaderLine.java:91)
	at htsjdk.variant.vcf.VCFAltHeaderLine.<init>(VCFAltHeaderLine.java:19)
	at htsjdk.variant.vcf.AbstractVCFCodec.getAltHeaderLine(AbstractVCFCodec.java:276)
	at htsjdk.variant.vcf.AbstractVCFCodec.parseHeaderFromLines(AbstractVCFCodec.java:204)
	at htsjdk.variant.vcf.VCFCodec.readActualHeader(VCFCodec.java:111)
	at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:79)
	at htsjdk.tribble.AsciiFeatureCodec.readHeader(AsciiFeatureCodec.java:37)
	at htsjdk.tribble.TribbleIndexedFeatureReader.readHeader(TribbleIndexedFeatureReader.java:262)
	at htsjdk.tribble.TribbleIndexedFeatureReader.<init>(TribbleIndexedFeatureReader.java:103)
	at htsjdk.tribble.TribbleIndexedFeatureReader.<init>(TribbleIndexedFeatureReader.java:128)
	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:121)
	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:81)
	at htsjdk.variant.vcf.VCFFileReader.<init>(VCFFileReader.java:145)
	at htsjdk.variant.vcf.VCFFileReader.<init>(VCFFileReader.java:95)
	at net.maizegenetics.phgv2.api.HaplotypeGraph.processFiles(HaplotypeGraph.kt:174)
	at net.maizegenetics.phgv2.api.HaplotypeGraph.access$processFiles(HaplotypeGraph.kt:18)
	at net.maizegenetics.phgv2.api.HaplotypeGraph$1.invokeSuspend(HaplotypeGraph.kt:45)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
```
Please let me know if you have any suggestion. Thank you.

**Comment by beantkapoor786** [comment]
Never mind, I was able to solve this issue by running the following command before loading the rJava package -
```R
options(java.parameters = "-Xmx8g")
```
I will close the issue and keep it here in case anyone else runs into this. Cheers.
